table DimChannels
	lineageTag: 35b14445-cb6c-46d0-8a65-00da4e7df425

	column SubChannelID
		dataType: int64
		formatString: 0
		lineageTag: 7dba3519-9c2d-4b65-84c9-23e75ee51035
		summarizeBy: none
		sourceColumn: SubChannelID

		annotation SummarizationSetBy = Automatic

	column Sub-channel
		dataType: string
		lineageTag: e8780171-5a74-46e2-884b-ec5a67b5e070
		summarizeBy: none
		sourceColumn: Sub-channel

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 6935db1d-1079-40b5-a30e-c987ec5b6d2f
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	partition DimChannels = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(DimSubChannel, {"ChannelID"}, DimChannel, {"ChannelID"}, "DimChannel", JoinKind.LeftOuter),
				    #"Expanded DimChannel" = Table.ExpandTableColumn(Source, "DimChannel", {"Channel"}, {"Channel"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded DimChannel",{"ChannelID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

