table DimEmployees
	lineageTag: 3acd4508-fb03-4563-923e-3352ec79d991

	column ID
		dataType: string
		lineageTag: cb8735cb-4487-4427-b9a1-ef7a4958498c
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 6c32b8cf-4526-416e-86ef-dbfcdb5725c3
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: 2ac379dd-8c76-4c7b-a7e2-d8b60ffa1bc1
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: 8649a4f9-1cd6-4799-ad62-7a031ad9ebb3
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	partition DimEmployees = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\olayi\Desktop\Data\Power BI\Foresight\Assets-230511-120519\PharmDataset-230517-152700.xlsx"), null, true),
				    DimEmployees_Sheet = Source{[Item="DimEmployees",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(DimEmployees_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", type text}, {"Name", type text}, {"Manager", type text}, {"Team", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

